'use strict';
const CATEGORIES = [
 {name:'Demographics',cue:'The who',symbol:'01 / WHO',examples:'Age, gender, income, education, occupation',detail:'Characteristics describing who people are. An age or gender does not tell you someone’s interests, ability or preferences.'},
 {name:'Psychographics',cue:'The why',symbol:'02 / WHY',examples:'Values, beliefs, lifestyle, personality, interests',detail:'What matters to people and what motivates them. Use stated preferences or research; do not infer someone’s beliefs from their appearance.'},
 {name:'Geographics',cue:'The where',symbol:'03 / WHERE',examples:'Country, city, climate, urban or rural',detail:'Where people live or use a service. Location can affect language, delivery and relevant content. Rural location alone does not prove a slow connection.'},
 {name:'Behavioural',cue:'The how',symbol:'04 / HOW',examples:'Buying habits, brand loyalty, usage rate, benefits sought',detail:'How people use, choose or buy a service, including the benefits they seek. A broad value such as independence is psychographic; wanting next-day delivery from a purchase is a benefit sought.'}
];
const CLUES = [
 ['Spotify','A listener is 19 years old.',0,'Age is demographic. It does not establish what music this person enjoys.','Use research about needs before choosing imagery or language.'],
 ['Roblox','A player says creative self-expression matters to them.',1,'This is a stated value: why an experience appeals to them.','Avatar customisation may support that motivation.'],
 ['Amazon','A shopper lives in the United Kingdom.',2,'Country is geographic, even though it can influence buying conditions.','Show the appropriate currency and delivery information.'],
 ['YouTube','A viewer watches tutorials every evening.',3,'This describes usage frequency: what the person does.','Continue-watching links could reduce repeat navigation.'],
 ['Google','A user describes her gender as female.',0,'Gender is demographic. It does not tell you which colours or topics she prefers.','Test inclusive content; do not turn gender into a design stereotype.'],
 ['Amazon','A customer prefers companies that share their environmental values.',1,'Environmental values explain motivation, so this clue is psychographic.','Clear, substantiated product information may help this customer.'],
 ['Google','A visitor is searching from Exeter.',2,'A city is a geographic location.','Local results may be more useful than distant ones.'],
 ['Spotify','A listener renews the same music subscription every year.',3,'Repeatedly staying with the same service indicates brand loyalty.','Easy access to a saved library can support returning listeners.'],
 ['Amazon','A shopper’s annual income is £24,000.',0,'Income is demographic. Their actual spending choices still need evidence.','Transparent prices help budget decisions without assuming low income means low digital skill.'],
 ['YouTube','A viewer has a strong interest in repairing old computers.',1,'An interest is psychographic; it differs from a recorded viewing action.','Topic labels can help them find repair content.'],
 ['Amazon','A customer lives in a region with a hot, dry climate.',2,'Climate is geographic. Buying sun protection would be a separate behavioural clue.','Seasonally relevant content is a possible design response, to be tested.'],
 ['Amazon','A customer compares prices across three websites before buying.',3,'This is a buying habit: an observable action.','Visible prices and product details can make comparison easier.'],
 ['Google','A user is studying for a Level 3 qualification.',0,'Education level is demographic. It does not prove expertise in every topic.','Clear result descriptions can help a learner judge relevance.'],
 ['Spotify','A listener describes their lifestyle as active and outdoorsy.',1,'Lifestyle is psychographic. It is not the same as a country or a usage rate.','Activity-based discovery could suit this stated preference.'],
 ['Amazon','A customer lives in a rural village rather than a city.',2,'Urban versus rural location is geographic. Connection quality must be checked separately.','Accurate delivery information may matter; do not invent restrictions.'],
 ['YouTube','A viewer wants quick, practical answers from the service.',3,'The benefit sought is a fast practical answer. This is behavioural segmentation.','Clear durations and searchable titles may reduce wasted time.'],
 ['Google','A user works as an electrician.',0,'Occupation is demographic. Searches for wiring guides would be behavioural evidence.','Use explicit needs, not occupation alone, to decide what to prioritise.'],
 ['Roblox','A player describes themselves as adventurous and curious.',1,'A self-described personality is psychographic.','Discovery tools might appeal; confirm this with user research.'],
 ['YouTube','A viewer believes educational content should be freely accessible.',1,'A belief explains why they value a service.','Make access conditions clear; do not promise that all content is free.'],
 ['Spotify','A listener plays the same saved playlist on every commute.',3,'This is a repeated usage pattern. The reason they like that music is not stated.','A prominent library shortcut could save time.']
];
const SOURCES = [
 {name:'Pearson — BTEC National IT specification, Unit 6 (printed pp. 57–65)',url:'https://qualifications.pearson.com/content/dam/pdf/BTEC-Nationals/Information-Technology/2016/specification-and-sample-assessments/specification-pearson-btec-level-3-national-extended-certificate-in-information-technology.pdf',note:'Learning aim A: compare website design for audiences and purposes; analyse and evaluate design, creativity, performance and client requirements.'},
 {name:'Spotify — Find playlists',url:'https://support.spotify.com/us/article/find-playlists/',note:'Spotify describes playlists informed by listening habits, including saves and skips.'},
 {name:'YouTube — How recommendations work',url:'https://support.google.com/youtube/answer/16089387?hl=en',note:'YouTube describes watch history as a recommendation signal, especially on its homepage.'},
 {name:'Google — Location and Search',url:'https://support.google.com/websearch/answer/179386?hl=en',note:'Google explains how location can affect search results.'},
 {name:'Roblox — What is Roblox?',url:'https://about.roblox.com/what-is-roblox',note:'Roblox describes experiences and self-expression features.'},
 {name:'Amazon UK — Customer reviews',url:'https://www.aboutamazon.co.uk/news/retail/update-on-customer-reviews',note:'Amazon explains the role of reviews in informed purchase decisions. This is a historical feature explanation, not current audience statistics.'}
];
const BRANDS = [
 {name:'Roblox',url:'https://www.roblox.com/',source:4,purpose:'Discover and participate in experiences; express an identity.',feature:'Self-expression and experience discovery',principle:'Visual hierarchy, navigation and customisation'},
 {name:'Spotify',url:'https://open.spotify.com/',source:1,purpose:'Discover and listen to audio; retain listeners.',feature:'Playlists informed by listening habits',principle:'Personalisation, consistency and navigation'},
 {name:'Amazon',url:'https://www.amazon.co.uk/',source:5,purpose:'Find, compare and buy products.',feature:'Customer reviews supporting purchase decisions',principle:'Information hierarchy, trust and usability'},
 {name:'Google',url:'https://www.google.com/',source:3,purpose:'Find relevant information and services.',feature:'Location can influence search results',principle:'Clarity, whitespace and relevance'},
 {name:'YouTube',url:'https://www.youtube.com/',source:2,purpose:'Find and watch video; support creators and returning viewers.',feature:'Recommendations can use watch history',principle:'Discovery, visual hierarchy and user control'}
];
// All design briefs and their scoring are authored classroom simulations, not brand analytics.
const MISSIONS = [
 {brand:0,title:'Let creativity lead',client:'Help new visitors find a suitable experience and understand avatar choices.',facts:['16-year-old college student','Values creativity and self-expression','Lives in a UK city','Returns daily; explores with friends'],need:'A first-time visitor must be able to understand choices without a crowded screen.',options:[
 ['Clear experience categories',2,4,'Navigation','Group experiences under clear labels.','Supports discovery without requiring prior knowledge.','Categories can oversimplify; test the labels with new users.'],
 ['Avatar preview with clear controls',2,4,'Customisation','Preview a choice before confirming it.','Connects the stated self-expression value to a visible interaction.','Preview media adds weight; optimise assets and provide text labels.'],
 ['Readable labels and keyboard access',2,4,'Accessibility','Make the main choices understandable and operable.','Helps more visitors complete the client’s discovery task.','Test keyboard order and contrast; appearance alone is insufficient.'],
 ['Full-screen autoplay trailer',3,1,'Multimedia','Start an animation before showing any choices.','May communicate atmosphere, but delays the discovery task.','Motion, data use and forced waiting can exclude visitors.'],
 ['Use one colour for all teenagers',1,0,'Assumption','Choose colours solely from the visitor’s age.','Age alone provides no evidence of colour preference.','Research preferences and prioritise contrast.'],
 ['Search with useful empty results',2,3,'Usability','Help users recover when a search finds nothing.','Gives a direct route for visitors who already know what they want.','A new visitor may not yet know what to search for.']
 ]},
 {brand:1,title:'The daily listening shortcut',client:'Help returning listeners reach familiar audio quickly while discovering something new.',facts:['20-year-old university student','Values discovery; enjoys an active lifestyle','Lives in Bristol, UK','Listens daily and frequently replays saved playlists'],need:'The listener uses a small screen on a commute and wants fewer steps to a saved playlist.',options:[
 ['Prominent library shortcut',2,4,'Navigation','Place saved audio within easy reach.','Responds to the repeated listening habit and reduces navigation effort.','Avoid crowding the interface with too many shortcuts.'],
 ['Explain recommendation choices',2,4,'Personalisation','Label suggestions and provide a way to adjust them.','Supports discovery and gives listeners more control.','Personalisation may repeat familiar content and depends on useful signals.'],
 ['Responsive, labelled controls',2,4,'Accessibility','Keep playback actions readable and usable on a small screen.','Supports the brief’s mobile task without relying on tiny icons.','Verify keyboard access and touch targets on actual devices.'],
 ['Large animated background',3,1,'Multimedia','Animate the entire player backdrop.','Could establish a mood but does not shorten the route to a playlist.','Extra rendering and motion can obstruct playback controls.'],
 ['Recommend only by gender',1,0,'Assumption','Select music using a demographic label alone.','Gender is not reliable evidence of musical taste.','Use expressed preferences and user-controlled discovery.'],
 ['Manual genre filter',2,3,'User control','Let the listener browse a chosen genre.','Offers discovery even without a rich listening history.','Genre labels overlap and can hide cross-genre music.']
 ]},
 {brand:2,title:'Confidence before checkout',client:'Help visitors compare products and make an informed purchase.',facts:['Apprentice with limited disposable income','Values reliability and avoiding waste','Lives in rural Devon, UK','Compares prices and seeks dependable delivery'],need:'The shopper wants to judge total cost, delivery and product suitability before committing.',options:[
 ['Clear total price and delivery',2,4,'Information hierarchy','Show costs and delivery information before checkout.','Supports comparison and the stated benefit sought.','Delivery estimates depend on address and stock; avoid unsupported promises.'],
 ['Readable reviews and product details',2,4,'Trust and usability','Make supporting product information easy to compare.','Helps users assess suitability and may reduce unsuitable purchases.','Reviews are not guaranteed truth; show context and use other evidence.'],
 ['Accessible comparison layout',2,4,'Responsive design','Keep key specifications readable on narrow screens.','Enables side-by-side decisions without clipped text.','Tables need a mobile alternative and screen-reader testing.'],
 ['Video above every product detail',3,1,'Multimedia','Load a large video before the price and specifications.','May demonstrate a product but delays this shopper’s priorities.','Media can increase loading time and distract from total cost.'],
 ['Hide fees until the last step',1,0,'Persuasion','Reveal additional costs only after details are entered.','Undermines the client brief’s informed purchase goal.','May cause abandonment and reduce trust.'],
 ['Save a comparison shortlist',2,3,'Interaction','Let a visitor retain items for later comparison.','Supports a considered purchase across multiple visits.','Explain how long saved information remains available.']
 ]},
 {brand:3,title:'Find somewhere nearby',client:'Help visitors quickly find a relevant local service and assess the result.',facts:['Working adult; electrician','Values independence and clear information','Currently in Exeter, UK','Searches occasionally and wants a nearby repair service'],need:'The visitor needs useful local information but must be able to correct the location.',options:[
 ['Visible, editable location',2,4,'Relevance and control','Show which area the results refer to.','Uses geography while letting the visitor correct an inaccurate assumption.','Estimated location can be wrong; provide a manual alternative.'],
 ['Clear result titles and descriptions',2,4,'Hierarchy','Make relevant result details easy to scan.','Helps the visitor judge relevance before opening a page.','A snippet does not prove the service is reliable or currently available.'],
 ['Lightweight responsive results',2,4,'Performance','Prioritise useful text and usable controls.','Reduces unnecessary content and supports quick information finding.','Measure performance; visual simplicity alone does not prove speed.'],
 ['Decorative video before results',3,1,'Multimedia','Show a brand film before local results appear.','May promote the brand but interrupts the immediate search task.','Extra waiting conflicts with finding a service quickly.'],
 ['Assume the user is in London',1,0,'Assumption','Use one city for every UK visitor.','Country does not identify the user’s city.','Allow accurate location selection.'],
 ['Distance and opening-time filters',2,3,'Navigation','Allow refinement using useful constraints.','Could improve task fit when reliable information exists.','Opening times can be stale; indicate uncertainty.']
 ]},
 {brand:4,title:'Learn it, then leave',client:'Help learners find a suitable tutorial, understand it and control what plays next.',facts:['17-year-old Level 3 IT student','Interested in repairing computers; values free learning','Lives in the UK','Watches tutorials frequently and seeks quick practical answers'],need:'The learner needs a relevant tutorial with clear steps, not an endless distraction.',options:[
 ['Clear title, duration and chapters',2,4,'Navigation and hierarchy','Help a learner judge scope and jump to a step.','Matches the benefit sought and reduces time spent locating an answer.','Chapters require accurate labels and editorial effort.'],
 ['Captions and transcript access',2,4,'Accessibility','Offer readable alternatives when available.','Supports learners who cannot hear audio or need to revisit a term.','Automatic captions can contain errors and need checking.'],
 ['Visible autoplay and history controls',2,4,'User control','Let the learner manage continuation and personalisation.','Supports a focused session and an informed choice about recommendations.','Some users may prefer automatic continuation; preserve choice.'],
 ['More autoplay with hidden controls',3,1,'Engagement','Prioritise continuous viewing over clear stopping controls.','Could increase viewing time but conflicts with the brief’s learner control.','Time spent is not proof of learning or satisfaction.'],
 ['Recommend by age alone',1,0,'Assumption','Assume all 17-year-olds want the same topic.','Age cannot establish subject interests or skill level.','Use explicit topics and appropriate user-controlled signals.'],
 ['Topic filters for search',2,3,'Discovery','Offer a direct route to a technical topic.','Useful when the learner knows what they need.','A beginner may not yet know the correct technical term.']
 ]}
];
const CLAIMS = [
 {brand:'Roblox',claim:'“Teenagers use Roblox, so every teenager will prefer a busy, neon website.”',answers:['Approve: age predicts visual taste.','Challenge: test preferences and usability with the intended segment.','Approve if a competitor uses neon.'],correct:1,why:'Demographics do not prove psychographic preferences. Contrast, readable text and task success require evidence, whatever the colour palette.'},
 {brand:'Spotify + YouTube',claim:'“Both recommend content, so their website designs meet exactly the same needs.”',answers:['Agree: recommendations make the sites identical.','Compare only their logos.','Compare the audio and video tasks, navigation and user control for a defined audience.'],correct:2,why:'A shared feature is a comparison starting point. P1 preparation needs similarities and differences linked to audience and purpose.'},
 {brand:'Google',claim:'“The homepage looks simple, which proves it is the fastest website.”',answers:['Measure loading and task performance under comparable conditions.','Accept it: less visible content always means faster code.','Count the number of colours instead.'],correct:0,why:'Appearance cannot prove measured speed. Network, device, scripts, caching and content all matter. Separate a performance prediction from a test result.'},
 {brand:'Amazon',claim:'“Readable reviews may help cautious shoppers assess suitability and support the client’s sales goal, but reviews can be misleading.”',answers:['Reject: analysis must only list features.','Keep the causal explanation; add a specific observation and evidence for the trade-off.','Remove the limitation so the site sounds better.'],correct:1,why:'This links a design choice to user and client outcomes. Evidence and a reasoned judgement strengthen analysis and evaluation; the predicted sales effect is not a measured result.'},
 {brand:'YouTube',claim:'“More viewing time proves a tutorial website is better for students.”',answers:['Agree: minutes watched are the only useful measure.','Reject all recommendations permanently.','Judge learning task success alongside engagement, accessibility and user control.'],correct:2,why:'Client and user goals can differ. Evaluate against the chosen purpose; longer sessions may mean interest, distraction or difficulty.'},
 {brand:'Google + Amazon',claim:'“A shopper lives in a rural village, so they definitely have slow internet.”',answers:['Challenge: location is known; connection speed needs separate evidence.','Agree: geography proves connection quality.','Move the clue into demographics.'],correct:0,why:'Rural location is geographic. Test on realistic connections without presenting an unsupported assumption as a fact.'},
 {brand:'Spotify',claim:'“They like discovering independent artists” and “they save five playlists a week” are the same type of clue.',answers:['Both are demographic.','The interest is psychographic; the saving frequency is behavioural.','Both are geographic.'],correct:1,why:'Motivation and behaviour may be related, but they are distinct evidence. Combining them can produce a more useful segment.'},
 {brand:'Amazon + Roblox',claim:'“Amazon is best because I like it. No further comparison is needed.”',answers:['Agree: evaluation is just personal preference.','Replace the opinion with a star rating.','Judge each site against its purpose, audience and client goals; weigh strengths and limitations.'],correct:2,why:'Different purposes prevent a simple universal winner. A justified conclusion should use observed design evidence, consequences and trade-offs.'}
];
const WRITING = [
 ['compare','P1 practice · Compare','Compare the two websites using at least two design principles. Explain a similarity and a difference, linking both to the defined audience and each site’s purpose.','Both sites use… On site A… whereas site B… This suits the audience because…'],
 ['analyse','M1 practice · Analyse','For each site, explain how a specific design choice affects the user’s task and a client goal. Address creativity and performance with evidence, distinguishing predictions from measurements.','The design choice… helps/hinders… because… This could support the client’s goal of… The evidence is… A creative aspect is… Performance evidence or a test needed is…'],
 ['evaluate','D1 practice · Evaluate','Weigh strengths against limitations for each site. Reach a justified judgement about how well each meets its client requirements and audience needs. Prioritise an improvement and explain how you would test it.','For this audience and purpose… is effective because… However… On balance… The most valuable improvement would be… I would test it by…']
];

// Valid audience-to-feature links for the bounded matching activity. Accessibility
// can benefit any segment; these links do not infer a disability from a profile.
const CONNECTIONS = [
 {links:{0:[3],1:[1],2:[0,1,2,3],5:[3]},outcomes:['Help visitors discover suitable experiences and understand avatar choices.','Keep visitors watching a trailer before they can make a choice.','Increase the number of products added to a shopping basket.']},
 {links:{0:[3],1:[1],2:[0,1,2,3],5:[1]},outcomes:['Help returning listeners reach familiar audio and discover something new.','Make every listener use the same playlist regardless of taste.','Help shoppers compare delivery charges before checkout.']},
 {links:{0:[0,2,3],1:[1,3],2:[0,1,2,3],5:[3]},outcomes:['Help shoppers compare products and make an informed purchase.','Keep product costs hidden until shoppers have entered their details.','Help players choose an avatar for a new experience.']},
 {links:{0:[2],1:[1,3],2:[0,1,2,3],5:[2,3]},outcomes:['Help visitors find and assess a relevant local service quickly.','Make all visitors search within London, wherever they are.','Increase the time spent browsing music playlists.']},
 {links:{0:[3],1:[0,1,2,3],2:[1,3],5:[1]},outcomes:['Help learners find and understand a suitable tutorial with control over playback.','Keep learners watching automatically even when their task is finished.','Help shoppers compare product delivery options.']}
];

// Concise cards for the explanation builder. Indices match each brief's options.
const BENEFITS = [
 ['Find experiences through clear categories.','See how an avatar choice expresses their style.','Read and operate the main choices more easily.','Watch an atmosphere-setting trailer before making choices.','See colours chosen from their age alone.','Recover from an unsuccessful search.'],
 ['Reach a saved playlist in fewer steps.','Discover audio with more control over suggestions.','Use labelled playback controls on a small screen.','Watch a moving background while listening.','Receive music selected from gender alone.','Browse a music genre they choose.'],
 ['Compare the full cost and delivery before committing.','Assess whether a product is suitable using reviews and details.','Read and compare specifications on a narrow screen.','Watch a product video before seeing the price.','Enter their details before finding out all the fees.','Return to a shortlist for a considered comparison.'],
 ['Correct the area used for local results.','Scan result details before opening a page.','Reach useful results without unnecessary page content.','Watch a brand film before finding a service.','See London results regardless of their actual city.','Refine local results by distance and opening time.'],
 ['Judge a tutorial’s scope and jump to a specific step.','Read the content when audio is unavailable or unclear.','Control what plays next and how history is used.','Keep watching automatically after their task is finished.','See topics selected from age alone.','Find a tutorial on a topic they already know.']
];
